awslabs/amazon-kinesis-client-python

samples/amazon_kclpy_helper.py, samples/sample_kclpy_app.py, samples/sample_kinesis_wordputter.py, setup.py
It doesn't seem like much work to also support Python 3, so I added the support.
- Import print_function from \__future__ and change all print statements to function calls.
- Handle different import paths to urllib.urlretrieve/urllib.request.urlretrieve in setup.py
=> Add support for Python 3

.gitignore, setup.py
This was causing:
```
(amazon-kinesis-client-python)➜  amazon-kinesis-client-python git:(master) ✗ python setup.py download_jars
running download_jars
Traceback (most recent call last):
File "setup.py", line 253, in <module>
zip_safe=False,
File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
dist.run_commands()
File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
self.run_command(cmd)
File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
cmd_obj.run()
File "setup.py", line 172, in run
downloader = MavenJarDownloader()
TypeError: __init__() takes …
```
=> fix(setup) Missing on_completion param for MavenJarDownloader

amazon_kclpy/messages.py
Previously the `record` that was passed was subscriptable as it was a simple dictionary.  This mechanism means that I am still able to do `record['data']` thereby maintaining backwards compatibility.
=> Make Record Subscriptable

setup.py
Updated to version 1.7.5 of the Amazon Kinesis Client, which brought in
additional updates to AWS Java SDK to 1.11.115.
=> Version Updates for Dependencies

amazon_kclpy/dispatch.py, amazon_kclpy/kcl.py, amazon_kclpy/messages.py, amazon_kclpy/v2/processor.py
@pfifer - Starting this PR to add capability in python client to handle shutdown requested call. Added for java in PR https://github.com/awslabs/amazon-kinesis-client/pull/174
=> Add shutdown requested implemention in python client.

amazon_kclpy/kcl.py, amazon_kclpy/messages.py, amazon_kclpy/v2/processor.py
Made sure new code tends towards PEP8, and updated copyright notices.
=> Code Style Cleanup, and Copyright Update

amazon_kclpy/kcl.py, amazon_kclpy/v2/processor.py
Existing users should be able to upgrade the library without issues.
Removed the abstract decorator to ensure that existing users'
applications continue to work normally.
=> shutdown_requested Should not be Abstract

amazon_kclpy/kcl.py, setup.py
Updated to the 1.9.0 release of the Kinesis Client Library (KCL) for Java.
Also moved to 1.5.0 since it's a minor bump on the KCL.
Includes an old commit to not catch exiting exceptions.
=>  Update to 1.9.0 release of the KCL

README.md
* Updated to version 1.9.0 of the Amazon Kinesis Client for Java
Version 1.9.0 now uses ListShards, instead of DescribeStream.
=> Release 1.5.0 of the Amazon Kinesis Client for Python

README.md, setup.py
N/A
* Updated to version 1.9.3 of the Amazon Kinesis Client Library for Java.
* https://github.com/awslabs/amazon-kinesis-client-python/pull/87
* Changed to now download jars from Maven using https.
* https://github.com/awslabs/amazon-kinesis-client-python/pull/87
* Changed to raise exception when downloading from Maven fails.
* https://github.com/awslabs/amazon-kinesis-client-python/pull/80
=> Release 1.5.1 of the Amazon Kinesis Client Library for Python

amazon_kclpy/dispatch.py, amazon_kclpy/kcl.py, amazon_kclpy/messages.py, samples/amazon_kclpy_helper.py, samples/sample_kclpy_app.py
There are small typos in:
- amazon_kclpy/dispatch.py
- amazon_kclpy/kcl.py
- amazon_kclpy/messages.py
- samples/amazon_kclpy_helper.py
- samples/sample_kclpy_app.py
Fixes:
- Should read `record` rather than `recod`.
- Should read `preceded` rather than `preceeded`.
- Should read `officially` rather than `officialy`.
- Should read `disaggregated` rather than `deaggregated`.
- Should read `callable` rather than `callabe`.
- Should read `because` rather than `becasue`.
- Should read `appropriate` rather than `appropiate`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

README.md, setup.py
Upgrade dependencies version
* Upgraded multiple dependencies 
* Amazon Kinesis Client Library 2.3.9
* ch.qos.logback 1.2.7
*Testing:*
Ran amazon_kclpy_helper.py with -l logback.xml file below
```
<configuration>
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
<encoder>
<pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
</encoder>
</appender>
<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
<file>logFile.log</file>
<rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
<fileNamePattern>logFile.%d{yyyy-MM-dd}.log</fileNamePattern>
<maxHistory>30</maxHistory>
</rollingPolicy>
<encoder>
<pattern>%-4relative [%thread] %-5level …
```
=> Release 2.0.6

README.md, pom.xml, samples/sample_kinesis_wordputter.py, setup.py
- Prepare for KCL Python Release 2.1.0
- Upgrade Java dependencies to match KCL release v2.4.4
- Note that POM file is copied from KCL-NodeJS: https://github.com/awslabs/amazon-kinesis-client-nodejs/blob/master/pom.xml
*Testing*
- Local testing
```
python sample_kinesis_wordputter.py -r us-west-2 --stream kclpysample -w cat -w dog -w bird -w lobster -p 5
`python amazon_kclpy_helper.py --print_command \
--java /Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/bin/java \
--properties sample.properties`
```
- pytest
```
11 passed, 2 warnings in 0.17s
```
=> Prepare for KCL Python Release 2.1.0

pom.xml
* Required for using WebIdentityTokenCredentialsProvider which is necessary for using IRSA
* This was added in [this PR](https://github.com/awslabs/amazon-kinesis-client-python/pull/133) but removed [here](https://github.com/awslabs/amazon-kinesis-client-python/commit/bc09d8b853a1da57761387182814ee7d03ae708b)
[Related issue](https://github.com/awslabs/amazon-kinesis-client-python/issues/129)
=> Add aws-java-sdk-sts

.github/dependabot.yml
Updating the master branch with the correct package-ecosystem so that dependabot PRs can start being published for this repository
=> Update dependabot.yml to use pip package-ecosystem

.github/workflows/run-unit-tests.yml
1. Removed python 3.6 version from GH Actions as it is EoL and no longer supproted in ubunto latest. 
- See ongoing issue: https://github.com/actions/setup-python/issues/544
2. Added python verison 3.11 to be tested against
=> Updated Python Versions for GH Actions - Update run-unit-tests.yml

pom.xml, samples/sample.properties
- Updated Python sample.properties to support streamArn. This is an extension of the [KCL Java - Multilang PR](https://github.com/awslabs/amazon-kinesis-client/pull/1143) to support parsing streamName from streamArn.
- Upgraded KCL dependencies 
Config:
```
...
executableName = sample_kclpy_app.py
streamName = words
```
Output
```
2023-06-26 11:48:07,056 [main] INFO  s.a.k.m.MultiLangDaemonConfig [NONE] - Running PythonKCLSample to process stream words with executable sample_kclpy_app.py 
```
Config:
```
streamArn = arn:aws:kinesis:us-east-5:000000000000:stream/words
streamName = ignoreThisStream
```
Output
```
39:03,298 [main] INFO  s.a.k.m.MultiLangDaemonConfig [NONE] - Running PythonKCLSample to process stream words with executable sample_kclpy_app.py
``` …
=> Upgrade KCL Java dependency from 2.4.4 to 2.5.1 and Added streamArn support in KCL Python

README.md, setup.py
Updated version and README.md to prepare for version 2.1.2 (from 2.1.1)
=> Preparing KCL Python for new minor version 2.1.2

pom.xml, samples/sample.properties
N/A
Revbump KCL to `2.5.2` to enable NestedPropertyKey support.
=> Revbump KCL to `2.5.2` to enable NestedPropertyKey support.

README.md, setup.py
Updated version and README.md to prepare for version 2.1.3 (from 2.1.2)
=> Preparing KCL Python for new minor version 2.1.3

.github/workflows/run-unit-tests.yml
Update CI to use a specific macOS version as the latest has issues with older version of python for now
https://github.com/actions/setup-python/issues/856
=> Fix CI due to different macOS architecture

requirements.txt, setup.py
Updates the `boto` dependency to be `boto3`
`boto3` is used in the sample https://github.com/awslabs/amazon-kinesis-client-python/blob/master/samples/sample_kinesis_wordputter.py#L12
=> Update boto dependency to boto3

README.md, setup.py
*Issue #, if available:* N/A
*Description of changes:* Prepare for release 2.1.5. Updating release notes and version number.
=> Prepare for KCL Python release 2.1.5

requirements.txt
[Issue 250](https://github.com/awslabs/amazon-kinesis-client-python/issues/250)
Modifies requirements.txt to make argparse only required for python versions <= 3.1
=> Only install argparse for python versions <= 3.1.

README.md, pom.xml
Issue:
v3.0.0 release of Python Multilang had hanging dependencies on `com.amazonaws` that were intended to be removed. 
When running `setup.py download_jars`, users may see a message like...
> RuntimeError: The following jars were not installed because they were not
present in this package at the time of installation:
amazon_kclpy/jars/aws-java-sdk-core-${aws-java-sdk.version}.jar
amazon_kclpy/jars/aws-java-sdk-sts-${aws-java-sdk.version}.jar
This doesn't affect the rest of the installation, but may make it more
difficult for you to run the sample app and get started.
**This can be safely ignored and subsequent steps of running the KCL will work as expected**. However, this is a deceptive error that will mislead users.
Removes those hanging dependencies so the error does not appear, …
=> Update dependencies for deprecated sdk1 and bumped kcl dependencies

README.md, setup.py
Fixes #258
* New lease assignment / load balancing algorithm
* KCL 3.x introduces a new lease assignment and load balancing algorithm. It assigns leases among workers based on worker utilization metrics and throughput on each lease, replacing the previous lease count-based lease assignment algorithm.
* When KCL detects higher variance in CPU utilization among workers, it proactively reassigns leases from over-utilized workers to under-utilized workers for even load balancing. This ensures even CPU utilization across workers and removes the need to over-provision the stream processing compute hosts.
* Optimized DynamoDB RCU usage
* KCL 3.x optimizes DynamoDB read capacity unit (RCU) usage on the lease table by implementing a global secondary index with leaseOwner as the partition key. This …
=> Upgrade to v3.0.1

README.md, pom.xml, setup.py
=> Upgrade to KCL 2.6.1

.github/workflows/run-unit-tests.yml
- 3.7 ubuntu is not used and python 3.7 is EOL
- Go back to macOS-latest platform
=> Remove python 3.7 from CI and use macOS-latest

.github/workflows/run-unit-tests.yml, README.md, pom.xml, samples/sample.properties, setup.py
*Description of changes:* Prepare for release 2.2.0. Updating release notes, sample.properties and version number.
* [#1444](https://github.com/awslabs/amazon-kinesis-client/pull/1444) Fully remove dependency on the AWS SDK for Java 1.x which will reach [end-of-support by December 31st, 2025](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/).
* The Glue Schema Registry integration functionality no longer depends on AWS SDK for Java 1.x. Previously, it required this as a transient dependency.
* Multilangdaemon has been upgraded to use AWS SDK for Java 2.x. It no longer depends on AWS SDK for Java 1.x.
* [#89](https://github.com/awslabs/amazon-kinesis-client-ruby/pull/89) Upgrade logback.version from 1.3.14 to 1.5.16
* …
=> Release v2.2.0

README.md, pom.xml, setup.py
[KCL 3.0.2 Changelog](https://github.com/awslabs/amazon-kinesis-client/blob/5263b4227ce7210d52bec6817191d43f047cd1b2/CHANGELOG.md) Upgrade KCL and KCL-Multilang dependencies from 3.0.0 to 3.0.2
https://github.com/awslabs/amazon-kinesis-client-python/pull/266 Upgrade netty.version from 4.1.108.Final to 4.1.118.Final
https://github.com/awslabs/amazon-kinesis-client-python/pull/265 Upgrade logback.version from 1.3.14 to 1.5.16
=> Prepare for 3.0.2 release

README.md, pom.xml, setup.py
* Downgrade logback from 1.5.16 to 1.3.15 to maintain JDK 8 compatability
=> Prepare for 3.0.3 release

README.md, setup.py
#209 
This PR add the ability to set a unique URL to download the required Jars from. Unlike #216, this adds the ability to set the entire URL while making sure the env name is unique.
This PR is specifically useful for teams that need to use a private Artifactory or hub to download the jars.
=> Add ability to set mvn repo search URL with a Unique ENV Variable

README.md, setup.py
* https://github.com/awslabs/amazon-kinesis-client-python/pull/318 Upgrade io.netty:netty-codec from 4.1.118.Final to 4.1.125.Final
* https://github.com/awslabs/amazon-kinesis-client-python/pull/304 Upgrade com.fasterxml.jackson.core:jackson-core from 2.13.5 to 2.15.0
Applied above commits to v2.x branch in https://github.com/awslabs/amazon-kinesis-client-python/pull/319
=> Release v2.2.2

README.md, setup.py
* [#325](https://github.com/awslabs/amazon-kinesis-client-python/pull/325) Update Maven repository in setup to repo1 domain, aligning with 3x version
* [#325](https://github.com/awslabs/amazon-kinesis-client-python/pull/325) Upgrade amazon-kinesis-client from 2.7.0 to 2.7.2
* [#325](https://github.com/awslabs/amazon-kinesis-client-python/pull/325) Upgrade aws-sdk from 2.25.64 to 2.33.0
* [#325](https://github.com/awslabs/amazon-kinesis-client-python/pull/325) Upgrade org.apache.commons:commons-lang3 from 3.14.0 to 3.18.0
* [#325](https://github.com/awslabs/amazon-kinesis-client-python/pull/325) Upgrade netty.version from 4.1.125 to 4.2.4.Final
=> Release v2.2.3
