awslabs/amazon-kinesis-client-python

setup.py

When the library is being installed in a virtual environment on macOS, or Windows the jars aren't correct installed (See Issue #33).  This overrides the bdist_wheel target which is called during installation of the library into a virtual environment.

Handle Installation to Virtual Environments for macOS, and Windows

---

README.md
setup.py

PR #39: Make record objects subscriptable for backwards compatibility.

Release 1.4.3 of the Amazon Kinesis Client for Python

---

README.md

* [PR #47]: Update to release 1.7.5 of the Amazon Kinesis Client.
* Additionally updated to version 1.11.115 of the AWS Java SDK.
* Fixes [Issue #43].
* Fixes [Issue #27].

Release 1.4.4 of the Amazon Kinesis Client Library for Python

---

amazon_kclpy/dispatch.py
test/__init__.py
test/conftest.py
test/test_amazon_kclpy.py
test/test_amazon_kclpy_input_output_integration.py
test/utils.py

Removed some tests that don't make sense, and updated all tests so that they should work with either Python2.7 or Python3 (Tested on Python 3.5)

Update tests to work with Python 3

---

README.md

* Updated to version 2.1.2 of the Amazon Kinesis Client Library for Java.
This update also includes version 2.4.0 of the AWS Java SDK.
* PR #92

Release 2.0.1 of the Amazon Kinesis Client Library for Python

---

LICENSE.txt
README.md
amazon_kclpy/__init__.py
amazon_kclpy/checkpoint_error.py
amazon_kclpy/dispatch.py
amazon_kclpy/kcl.py
amazon_kclpy/messages.py
amazon_kclpy/v2/__init__.py
amazon_kclpy/v2/processor.py
amazon_kclpy/v3/__init__.py
amazon_kclpy/v3/processor.py
samples/__init__.py
samples/amazon_kclpy_helper.py
samples/sample_kclpy_app.py
samples/sample_kinesis_wordputter.py
scripts/build_deps.py
setup.py
test/__init__.py
test/conftest.py
test/test_amazon_kclpy.py
test/utils.py
test/v3/__init__.py
test/v3/delegate_test.py

Relicense to Apache-2.0

---

README.md
setup.py

updated readme

---

README.md
setup.py

N/A
ran into Failure running python setup.py download_jars. Fix typo.

Fix typo in version upgrade

---

.github/workflows/run-unit-tests.yml
requirements.txt
test_requirements.txt

Signed-off-by: Rex Chen <shuningc@amazon.com>

Move test dependencies to test_requirements.txt

---

setup.py

- Release 2.0.5
- Fix Typo for release
In moving dependencies accidentally introduced misplaced ','
Fix typo

Fix Typo for release

---

samples/sample.properties

N/A
Add comment for initialPositionInStreamExtended

Add comment for initialPositionInStreamExtended

---

pom.xml
setup.py

*Issue #, if available:* N/A
*Description of changes:* Upgrade KCL version to 2.5.8.

upgrade KCL version from 2.5.2 to 2.5.8

---

pom.xml

Attempting to resolve the following security vulnerability: https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-21634

Updated ion-java from 1.5.1 to 1.11.4

---

README.md

*Issue #, if available:* N/A
*Description of changes:* Updating release notes for version 2.1.4. 

Update release notes for 2.1.4

---

pom.xml

#247 
Fixes dependency errors
- Matches AWS SDK version to java KCL AWS SDK version
- Adds Java SDKs necessary to run sample

Fix dependency versions

---

README.md
pom.xml
samples/sample.properties
setup.py

Update configuration files to be compatible with KCLv3

Upgrade to KCL v3.0.0

---

pom.xml

Upgrade logback to 1.5.16

---

README.md
pom.xml
setup.py

* Downgrade logback from 1.5.16 to 1.3.15 to maintain JDK 8 compatability

Prepare for 2.2.1 release

---

.github/dependabot.yml
.github/workflows/privileged-run.yml
pom.xml

Adds dependabot auto-merge and an option to manually run workflows without making a pull request. Updated documentation describing workflow.

Add dependabot auto-merge and workflow dispatch; update documentation

---

README.md
pom.xml
setup.py

*Description of changes:* Preparing for KCL Python release 3.0.4

Prepare for release 3.0.4

---

pom.xml
setup.py

*Description of changes:* Upgrade verison number to 3.0.5 

Upgrade verison number to 3.0.5 

---

README.md

*Description of changes:* Change 3.0.4 in release notes to 3.0.5 

Correct release notes

---

.github/workflows/privileged-run.yml

github actions pull_request patch

---

samples/sample.properties

Added multi-lang support for leaseAssignmentIntervalMillis

---

pom.xml

* Upgrade amazon-kinesis-client from 3.1.1 to 3.1.3
* Upgrade aws-sdk from 2.25.64 to 2.33.0
* Upgrade org.apache.commons:commons-lang3 from 3.14.0 to 3.18.0
* Upgrade netty.version from 4.1.125 to 4.2.4.Final

Upgrade KCL version, upgrade aws sdk, upgrade apache commons-lang3, upgrade netty
